# Generated by Django 5.0.7 on 2024-07-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0003_remove_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
