# Generated by Django 5.0.7 on 2024-08-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0004_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
